#WAS
spring.profiles.active=prod
server.port=11000

#MariaDB
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://{HOST}:3306/mintDB
spring.datasource.username={USERNAME}
spring.datasource.password={PASSWORD}

# DTO Location
mybatis.type-aliases-package=kopo.poly.dto

# SQL Query Location
mybatis.mapper-locations=classpath:mapper/*.xml

#thymeleaf Setting
spring.thymeleaf.cache=false
spring.thymeleaf.check-template-location=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

spring.devtools.livereload.enabled=true
spring.devtools.restart.enabled=true


#Mail Sender
spring.mail.host=smtp.naver.com
spring.mail.port=465
spring.mail.username={NAVER_ID}
spring.mail.password={NAVER_PASSWORD}
spring.mail.default-encoding=utf-8
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.naver.com


# File Setting
#file.upload-dir=/DiaryService/src/main/resources/static/images
file.upload-dir=/MintD/
#file.upload-dir=classpath:MDimg
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
